import: rubensworks/travis-presets:node-base.yml@master
install: npm install
script:
  - npm run build
  - touch build/.nojekyll
dist: trusty

cache:
  npm: true
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  on:
    branch: master
    node_js: "node"
